// ── Player database ──────────────────────────────────────────────────────────
const PLAYERS = [
  // Norge (I) – komplett VM-tropp 2026
  { name: 'Ørjan Håskjold Nyland', team: 'NOR', flag: '🇳🇴', info: 'Sevilla · Keeper' },
  { name: 'Egil Selvik', team: 'NOR', flag: '🇳🇴', info: 'Sarpsborg 08 · Keeper' },
  { name: 'Sander Tangvik', team: 'NOR', flag: '🇳🇴', info: 'Brann · Keeper' },
  { name: 'Kristoffer Ajer', team: 'NOR', flag: '🇳🇴', info: 'Brentford · Forsvar' },
  { name: 'Julian Ryerson', team: 'NOR', flag: '🇳🇴', info: 'Borussia Dortmund · Forsvar' },
  { name: 'David Møller Wolfe', team: 'NOR', flag: '🇳🇴', info: 'AZ Alkmaar · Forsvar' },
  { name: 'Fredrik Bjørkan', team: 'NOR', flag: '🇳🇴', info: 'Bodø/Glimt · Forsvar' },
  { name: 'Marcus Holmgren Pedersen', team: 'NOR', flag: '🇳🇴', info: 'Sassuolo · Forsvar' },
  { name: 'Torbjørn Heggem', team: 'NOR', flag: '🇳🇴', info: 'West Brom · Forsvar' },
  { name: 'Leo Skiri Østigård', team: 'NOR', flag: '🇳🇴', info: 'Stade Rennais · Forsvar' },
  { name: 'Sondre Langås', team: 'NOR', flag: '🇳🇴', info: 'Brann · Forsvar' },
  { name: 'Henrik Falchener', team: 'NOR', flag: '🇳🇴', info: 'Midtbane' },
  { name: 'Martin Ødegaard', team: 'NOR', flag: '🇳🇴', info: 'Arsenal · Kaptein' },
  { name: 'Sander Berge', team: 'NOR', flag: '🇳🇴', info: 'Fulham · Midtbane' },
  { name: 'Fredrik Aursnes', team: 'NOR', flag: '🇳🇴', info: 'Benfica · Midtbane' },
  { name: 'Patrick Berg', team: 'NOR', flag: '🇳🇴', info: 'Bodø/Glimt · Midtbane' },
  { name: 'Kristian Thorstvedt', team: 'NOR', flag: '🇳🇴', info: 'Sassuolo · Midtbane' },
  { name: 'Oscar Bobb', team: 'NOR', flag: '🇳🇴', info: 'Manchester City · Angrep' },
  { name: 'Andreas Schjelderup', team: 'NOR', flag: '🇳🇴', info: 'Benfica · Angrep' },
  { name: 'Antonio Nusa', team: 'NOR', flag: '🇳🇴', info: 'RB Leipzig · Angrep' },
  { name: 'Morten Thorsby', team: 'NOR', flag: '🇳🇴', info: 'Genoa · Midtbane' },
  { name: 'Jens Petter Hauge', team: 'NOR', flag: '🇳🇴', info: 'Angrep' },
  { name: 'Thelo Aasgaard', team: 'NOR', flag: '🇳🇴', info: 'Wigan · Midtbane' },
  { name: 'Erling Braut Haaland', team: 'NOR', flag: '🇳🇴', info: 'Manchester City · Spiss' },
  { name: 'Alexander Sørloth', team: 'NOR', flag: '🇳🇴', info: 'Atlético Madrid · Spiss' },
  { name: 'Jørgen Strand Larsen', team: 'NOR', flag: '🇳🇴', info: 'Crystal Palace · Spiss' },
  // Argentina (J)
  { name: 'Lionel Messi', team: 'ARG', flag: '🇦🇷', info: 'Inter Miami' },
  { name: 'Lautaro Martínez', team: 'ARG', flag: '🇦🇷', info: 'Inter' },
  { name: 'Julián Álvarez', team: 'ARG', flag: '🇦🇷', info: 'Atlético Madrid' },
  { name: 'Alejandro Garnacho', team: 'ARG', flag: '🇦🇷', info: 'Manchester United' },
  { name: 'Paulo Dybala', team: 'ARG', flag: '🇦🇷', info: 'Roma' },
  { name: 'Ángel Di María', team: 'ARG', flag: '🇦🇷', info: 'Benfica' },
  { name: 'Rodrigo De Paul', team: 'ARG', flag: '🇦🇷', info: 'Atlético Madrid' },
  // Brasil (C) – komplett VM-tropp 2026
  { name: 'Alisson', team: 'BRA', flag: '🇧🇷', info: 'Liverpool · Keeper' },
  { name: 'Ederson', team: 'BRA', flag: '🇧🇷', info: 'Fenerbahçe · Keeper' },
  { name: 'Weverton', team: 'BRA', flag: '🇧🇷', info: 'Grêmio · Keeper' },
  { name: 'Alex Sandro', team: 'BRA', flag: '🇧🇷', info: 'Flamengo · Forsvar' },
  { name: 'Bremer', team: 'BRA', flag: '🇧🇷', info: 'Juventus · Forsvar' },
  { name: 'Danilo', team: 'BRA', flag: '🇧🇷', info: 'Flamengo · Forsvar' },
  { name: 'Douglas Santos', team: 'BRA', flag: '🇧🇷', info: 'Zenit St. Petersburg · Forsvar' },
  { name: 'Gabriel Magalhães', team: 'BRA', flag: '🇧🇷', info: 'Arsenal · Forsvar' },
  { name: 'Roger Ibañez', team: 'BRA', flag: '🇧🇷', info: 'Al-Ahli · Forsvar' },
  { name: 'Léo Pereira', team: 'BRA', flag: '🇧🇷', info: 'Flamengo · Forsvar' },
  { name: 'Marquinhos', team: 'BRA', flag: '🇧🇷', info: 'Paris Saint-Germain · Forsvar' },
  { name: 'Wesley', team: 'BRA', flag: '🇧🇷', info: 'Roma · Forsvar' },
  { name: 'Bruno Guimarães', team: 'BRA', flag: '🇧🇷', info: 'Newcastle · Midtbane' },
  { name: 'Casemiro', team: 'BRA', flag: '🇧🇷', info: 'Manchester United · Midtbane' },
  { name: 'Danilo Santos', team: 'BRA', flag: '🇧🇷', info: 'Botafogo · Midtbane' },
  { name: 'Fabinho', team: 'BRA', flag: '🇧🇷', info: 'Al-Ittihad · Midtbane' },
  { name: 'Lucas Paquetá', team: 'BRA', flag: '🇧🇷', info: 'Flamengo · Midtbane' },
  { name: 'Endrick', team: 'BRA', flag: '🇧🇷', info: 'Lyon · Spiss' },
  { name: 'Gabriel Martinelli', team: 'BRA', flag: '🇧🇷', info: 'Arsenal · Angrep' },
  { name: 'Igor Thiago', team: 'BRA', flag: '🇧🇷', info: 'Brentford · Spiss' },
  { name: 'Luiz Henrique', team: 'BRA', flag: '🇧🇷', info: 'Zenit St. Petersburg · Angrep' },
  { name: 'Matheus Cunha', team: 'BRA', flag: '🇧🇷', info: 'Manchester United · Angrep' },
  { name: 'Neymar', team: 'BRA', flag: '🇧🇷', info: 'Santos · Angrep' },
  { name: 'Raphinha', team: 'BRA', flag: '🇧🇷', info: 'Barcelona · Angrep' },
  { name: 'Rayan', team: 'BRA', flag: '🇧🇷', info: 'Bournemouth · Angrep' },
  { name: 'Vinicius Júnior', team: 'BRA', flag: '🇧🇷', info: 'Real Madrid · Angrep' },
  // Frankrike (I) – komplett VM-tropp 2026
  { name: 'Mike Maignan', team: 'FRA', flag: '🇫🇷', info: 'AC Milan · Keeper' },
  { name: 'Brice Samba', team: 'FRA', flag: '🇫🇷', info: 'Rennes · Keeper' },
  { name: 'Robin Risser', team: 'FRA', flag: '🇫🇷', info: 'Lens · Keeper' },
  { name: 'Ibrahima Konaté', team: 'FRA', flag: '🇫🇷', info: 'Liverpool · Forsvar' },
  { name: 'Lucas Digne', team: 'FRA', flag: '🇫🇷', info: 'Aston Villa · Forsvar' },
  { name: 'Malo Gusto', team: 'FRA', flag: '🇫🇷', info: 'Chelsea · Forsvar' },
  { name: 'Lucas Hernandez', team: 'FRA', flag: '🇫🇷', info: 'Paris Saint-Germain · Forsvar' },
  { name: 'Theo Hernandez', team: 'FRA', flag: '🇫🇷', info: 'Al-Hilal · Forsvar' },
  { name: 'Jules Koundé', team: 'FRA', flag: '🇫🇷', info: 'Barcelona · Forsvar' },
  { name: 'Maxence Lacroix', team: 'FRA', flag: '🇫🇷', info: 'Crystal Palace · Forsvar' },
  { name: 'William Saliba', team: 'FRA', flag: '🇫🇷', info: 'Arsenal · Forsvar' },
  { name: 'Dayot Upamecano', team: 'FRA', flag: '🇫🇷', info: 'Bayern München · Forsvar' },
  { name: "N'Golo Kanté", team: 'FRA', flag: '🇫🇷', info: 'Fenerbahçe · Midtbane' },
  { name: 'Manu Koné', team: 'FRA', flag: '🇫🇷', info: 'Roma · Midtbane' },
  { name: 'Aurélien Tchouaméni', team: 'FRA', flag: '🇫🇷', info: 'Real Madrid · Midtbane' },
  { name: 'Warren Zaïre-Emery', team: 'FRA', flag: '🇫🇷', info: 'Paris Saint-Germain · Midtbane' },
  { name: 'Adrien Rabiot', team: 'FRA', flag: '🇫🇷', info: 'AC Milan · Midtbane' },
  { name: 'Marcus Thuram', team: 'FRA', flag: '🇫🇷', info: 'Inter · Angrep' },
  { name: 'Michael Olise', team: 'FRA', flag: '🇫🇷', info: 'Bayern München · Angrep' },
  { name: 'Kylian Mbappé', team: 'FRA', flag: '🇫🇷', info: 'Real Madrid · Angrep · Kaptein' },
  { name: 'Jean-Philippe Mateta', team: 'FRA', flag: '🇫🇷', info: 'Crystal Palace · Spiss' },
  { name: 'Désiré Doué', team: 'FRA', flag: '🇫🇷', info: 'Paris Saint-Germain · Angrep' },
  { name: 'Ousmane Dembélé', team: 'FRA', flag: '🇫🇷', info: 'Paris Saint-Germain · Angrep' },
  { name: 'Rayan Cherki', team: 'FRA', flag: '🇫🇷', info: 'Manchester City · Angrep' },
  { name: 'Maghnes Akliouche', team: 'FRA', flag: '🇫🇷', info: 'Monaco · Angrep' },
  { name: 'Bradley Barcola', team: 'FRA', flag: '🇫🇷', info: 'Paris Saint-Germain · Angrep' },
  // England (L) – komplett VM-tropp 2026
  { name: 'Jordan Pickford', team: 'ENG', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', info: 'Everton · Keeper' },
  { name: 'Dean Henderson', team: 'ENG', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', info: 'Crystal Palace · Keeper' },
  { name: 'James Trafford', team: 'ENG', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', info: 'Manchester City · Keeper' },
  { name: 'Reece James', team: 'ENG', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', info: 'Chelsea · Forsvar' },
  { name: 'Ezri Konsa', team: 'ENG', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', info: 'Aston Villa · Forsvar' },
  { name: 'Jarell Quansah', team: 'ENG', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', info: 'Bayer Leverkusen · Forsvar' },
  { name: 'John Stones', team: 'ENG', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', info: 'Manchester City · Forsvar' },
  { name: 'Marc Guéhi', team: 'ENG', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', info: 'Crystal Palace · Forsvar' },
  { name: 'Dan Burn', team: 'ENG', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', info: 'Newcastle · Forsvar' },
  { name: "Nico O'Reilly", team: 'ENG', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', info: 'Manchester City · Forsvar' },
  { name: 'Djed Spence', team: 'ENG', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', info: 'Tottenham · Forsvar' },
  { name: 'Tino Livramento', team: 'ENG', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', info: 'Newcastle · Forsvar' },
  { name: 'Declan Rice', team: 'ENG', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', info: 'Arsenal · Midtbane' },
  { name: 'Elliot Anderson', team: 'ENG', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', info: 'Nottingham Forest · Midtbane' },
  { name: 'Kobbie Mainoo', team: 'ENG', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', info: 'Manchester United · Midtbane' },
  { name: 'Jordan Henderson', team: 'ENG', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', info: 'Brentford · Midtbane' },
  { name: 'Morgan Rogers', team: 'ENG', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', info: 'Aston Villa · Midtbane' },
  { name: 'Jude Bellingham', team: 'ENG', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', info: 'Real Madrid · Midtbane' },
  { name: 'Eberechi Eze', team: 'ENG', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', info: 'Arsenal · Midtbane' },
  { name: 'Harry Kane', team: 'ENG', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', info: 'Bayern München · Spiss · Kaptein' },
  { name: 'Ivan Toney', team: 'ENG', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', info: 'Al-Ahli · Spiss' },
  { name: 'Ollie Watkins', team: 'ENG', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', info: 'Aston Villa · Spiss' },
  { name: 'Bukayo Saka', team: 'ENG', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', info: 'Arsenal · Angrep' },
  { name: 'Marcus Rashford', team: 'ENG', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', info: 'Barcelona · Angrep' },
  { name: 'Anthony Gordon', team: 'ENG', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', info: 'Newcastle · Angrep' },
  { name: 'Noni Madueke', team: 'ENG', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', info: 'Arsenal · Angrep' },
  // Spania (H) – komplett VM-tropp 2026
  { name: 'Unai Simón', team: 'ESP', flag: '🇪🇸', info: 'Athletic Club · Keeper' },
  { name: 'David Raya', team: 'ESP', flag: '🇪🇸', info: 'Arsenal · Keeper' },
  { name: 'Joan García', team: 'ESP', flag: '🇪🇸', info: 'Barcelona · Keeper' },
  { name: 'Pedro Porro', team: 'ESP', flag: '🇪🇸', info: 'Tottenham · Forsvar' },
  { name: 'Marcos Llorente', team: 'ESP', flag: '🇪🇸', info: 'Atlético Madrid · Forsvar' },
  { name: 'Aymeric Laporte', team: 'ESP', flag: '🇪🇸', info: 'Athletic Club · Forsvar' },
  { name: 'Pau Cubarsí', team: 'ESP', flag: '🇪🇸', info: 'Barcelona · Forsvar' },
  { name: 'Marc Pubill', team: 'ESP', flag: '🇪🇸', info: 'Atlético Madrid · Forsvar' },
  { name: 'Eric García', team: 'ESP', flag: '🇪🇸', info: 'Barcelona · Forsvar' },
  { name: 'Marc Cucurella', team: 'ESP', flag: '🇪🇸', info: 'Chelsea · Forsvar' },
  { name: 'Álex Grimaldo', team: 'ESP', flag: '🇪🇸', info: 'Bayer Leverkusen · Forsvar' },
  { name: 'Rodri', team: 'ESP', flag: '🇪🇸', info: 'Manchester City · Midtbane' },
  { name: 'Martín Zubimendi', team: 'ESP', flag: '🇪🇸', info: 'Arsenal · Midtbane' },
  { name: 'Pedri', team: 'ESP', flag: '🇪🇸', info: 'Barcelona · Midtbane' },
  { name: 'Mikel Merino', team: 'ESP', flag: '🇪🇸', info: 'Arsenal · Midtbane' },
  { name: 'Fabián Ruiz', team: 'ESP', flag: '🇪🇸', info: 'Paris Saint-Germain · Midtbane' },
  { name: 'Álex Baena', team: 'ESP', flag: '🇪🇸', info: 'Atlético Madrid · Midtbane' },
  { name: 'Gavi', team: 'ESP', flag: '🇪🇸', info: 'Barcelona · Midtbane' },
  { name: 'Nico Williams', team: 'ESP', flag: '🇪🇸', info: 'Athletic Club · Angrep' },
  { name: 'Mikel Oyarzabal', team: 'ESP', flag: '🇪🇸', info: 'Real Sociedad · Angrep' },
  { name: 'Ferran Torres', team: 'ESP', flag: '🇪🇸', info: 'Barcelona · Angrep' },
  { name: 'Borja Iglesias', team: 'ESP', flag: '🇪🇸', info: 'Celta Vigo · Spiss' },
  { name: 'Yeremy Pino', team: 'ESP', flag: '🇪🇸', info: 'Crystal Palace · Angrep' },
  { name: 'Dani Olmo', team: 'ESP', flag: '🇪🇸', info: 'Barcelona · Angrep' },
  { name: 'Lamine Yamal', team: 'ESP', flag: '🇪🇸', info: 'Barcelona · Angrep' },
  { name: 'Víctor Muñoz', team: 'ESP', flag: '🇪🇸', info: 'Angrep' },
  // Portugal (K) – komplett VM-tropp 2026
  { name: 'Diogo Costa', team: 'POR', flag: '🇵🇹', info: 'Porto · Keeper' },
  { name: 'José Sá', team: 'POR', flag: '🇵🇹', info: 'Wolverhampton · Keeper' },
  { name: 'Rui Silva', team: 'POR', flag: '🇵🇹', info: 'Sporting CP · Keeper' },
  { name: 'Ricardo Velho', team: 'POR', flag: '🇵🇹', info: 'Gençlerbirliği Ankara · Keeper' },
  { name: 'João Cancelo', team: 'POR', flag: '🇵🇹', info: 'Al-Hilal · Forsvar' },
  { name: 'Diogo Dalot', team: 'POR', flag: '🇵🇹', info: 'Manchester United · Forsvar' },
  { name: 'Rúben Dias', team: 'POR', flag: '🇵🇹', info: 'Manchester City · Forsvar' },
  { name: 'Nélson Semedo', team: 'POR', flag: '🇵🇹', info: 'Fenerbahçe · Forsvar' },
  { name: 'Gonçalo Inácio', team: 'POR', flag: '🇵🇹', info: 'Sporting CP · Forsvar' },
  { name: 'Nuno Mendes', team: 'POR', flag: '🇵🇹', info: 'Paris Saint-Germain · Forsvar' },
  { name: 'Matheus Nunes', team: 'POR', flag: '🇵🇹', info: 'Manchester City · Forsvar' },
  { name: 'Renato Veiga', team: 'POR', flag: '🇵🇹', info: 'Villarreal · Forsvar' },
  { name: 'Tomás Araújo', team: 'POR', flag: '🇵🇹', info: 'Benfica · Forsvar' },
  { name: 'Bruno Fernandes', team: 'POR', flag: '🇵🇹', info: 'Manchester United · Midtbane' },
  { name: 'João Neves', team: 'POR', flag: '🇵🇹', info: 'Paris Saint-Germain · Midtbane' },
  { name: 'Rúben Neves', team: 'POR', flag: '🇵🇹', info: 'Al-Hilal · Midtbane' },
  { name: 'Bernardo Silva', team: 'POR', flag: '🇵🇹', info: 'Manchester City · Midtbane' },
  { name: 'Vitinha', team: 'POR', flag: '🇵🇹', info: 'Paris Saint-Germain · Midtbane' },
  { name: 'Samuel Costa', team: 'POR', flag: '🇵🇹', info: 'Mallorca · Midtbane' },
  { name: 'Cristiano Ronaldo', team: 'POR', flag: '🇵🇹', info: 'Al-Nassr · Spiss · Kaptein' },
  { name: 'João Félix', team: 'POR', flag: '🇵🇹', info: 'Al-Nassr · Angrep' },
  { name: 'Gonçalo Guedes', team: 'POR', flag: '🇵🇹', info: 'Real Sociedad · Angrep' },
  { name: 'Francisco Trincão', team: 'POR', flag: '🇵🇹', info: 'Sporting CP · Angrep' },
  { name: 'Francisco Conceição', team: 'POR', flag: '🇵🇹', info: 'Juventus · Angrep' },
  { name: 'Rafael Leão', team: 'POR', flag: '🇵🇹', info: 'AC Milan · Angrep' },
  { name: 'Pedro Neto', team: 'POR', flag: '🇵🇹', info: 'Chelsea · Angrep' },
  { name: 'Gonçalo Ramos', team: 'POR', flag: '🇵🇹', info: 'Paris Saint-Germain · Spiss' },
  // Tyskland (E) – komplett VM-tropp 2026
  { name: 'Oliver Baumann', team: 'GER', flag: '🇩🇪', info: 'Hoffenheim · Keeper' },
  { name: 'Manuel Neuer', team: 'GER', flag: '🇩🇪', info: 'Bayern München · Keeper' },
  { name: 'Alexander Nübel', team: 'GER', flag: '🇩🇪', info: 'VfB Stuttgart · Keeper' },
  { name: 'Waldemar Anton', team: 'GER', flag: '🇩🇪', info: 'Borussia Dortmund · Forsvar' },
  { name: 'Nathaniel Brown', team: 'GER', flag: '🇩🇪', info: 'Eintracht Frankfurt · Forsvar' },
  { name: 'Pascal Groß', team: 'GER', flag: '🇩🇪', info: 'Borussia Dortmund · Midtbane' },
  { name: 'Joshua Kimmich', team: 'GER', flag: '🇩🇪', info: 'Bayern München · Midtbane · Kaptein' },
  { name: 'Felix Nmecha', team: 'GER', flag: '🇩🇪', info: 'Borussia Dortmund · Midtbane' },
  { name: 'Aleksandar Pavlović', team: 'GER', flag: '🇩🇪', info: 'Bayern München · Midtbane' },
  { name: 'David Raum', team: 'GER', flag: '🇩🇪', info: 'RB Leipzig · Forsvar' },
  { name: 'Antonio Rüdiger', team: 'GER', flag: '🇩🇪', info: 'Real Madrid · Forsvar' },
  { name: 'Nico Schlotterbeck', team: 'GER', flag: '🇩🇪', info: 'Borussia Dortmund · Forsvar' },
  { name: 'Angelo Stiller', team: 'GER', flag: '🇩🇪', info: 'VfB Stuttgart · Midtbane' },
  { name: 'Jonathan Tah', team: 'GER', flag: '🇩🇪', info: 'Bayern München · Forsvar' },
  { name: 'Malick Thiaw', team: 'GER', flag: '🇩🇪', info: 'AC Milan · Forsvar' },
  { name: 'Nadiem Amiri', team: 'GER', flag: '🇩🇪', info: 'Mainz 05 · Midtbane' },
  { name: 'Maximilian Beier', team: 'GER', flag: '🇩🇪', info: 'Borussia Dortmund · Angrep' },
  { name: 'Leon Goretzka', team: 'GER', flag: '🇩🇪', info: 'Bayern München · Midtbane' },
  { name: 'Kai Havertz', team: 'GER', flag: '🇩🇪', info: 'Arsenal · Angrep' },
  { name: 'Lennart Karl', team: 'GER', flag: '🇩🇪', info: 'Bayern München · Angrep' },
  { name: 'Jamie Leweling', team: 'GER', flag: '🇩🇪', info: 'VfB Stuttgart · Angrep' },
  { name: 'Jamal Musiala', team: 'GER', flag: '🇩🇪', info: 'Bayern München · Angrep' },
  { name: 'Leroy Sané', team: 'GER', flag: '🇩🇪', info: 'Bayern München · Angrep' },
  { name: 'Deniz Undav', team: 'GER', flag: '🇩🇪', info: 'VfB Stuttgart · Spiss' },
  { name: 'Florian Wirtz', team: 'GER', flag: '🇩🇪', info: 'Liverpool · Midtbane' },
  { name: 'Nick Woltemade', team: 'GER', flag: '🇩🇪', info: 'Newcastle · Spiss' },
  // Nederland (F)
  { name: 'Virgil van Dijk', team: 'NED', flag: '🇳🇱', info: 'Liverpool' },
  { name: 'Memphis Depay', team: 'NED', flag: '🇳🇱', info: 'Corinthians' },
  { name: 'Cody Gakpo', team: 'NED', flag: '🇳🇱', info: 'Liverpool' },
  { name: 'Xavi Simons', team: 'NED', flag: '🇳🇱', info: 'RB Leipzig' },
  { name: 'Donyell Malen', team: 'NED', flag: '🇳🇱', info: 'Dortmund' },
  { name: 'Wout Weghorst', team: 'NED', flag: '🇳🇱', info: 'Hoffenheim' },
  // Belgia (G) – komplett VM-tropp 2026
  { name: 'Thibaut Courtois', team: 'BEL', flag: '🇧🇪', info: 'Real Madrid · Keeper' },
  { name: 'Senne Lammens', team: 'BEL', flag: '🇧🇪', info: 'Manchester United · Keeper' },
  { name: 'Mike Penders', team: 'BEL', flag: '🇧🇪', info: 'Strasbourg · Keeper' },
  { name: 'Zeno Debast', team: 'BEL', flag: '🇧🇪', info: 'Sporting CP · Forsvar' },
  { name: 'Arthur Theate', team: 'BEL', flag: '🇧🇪', info: 'Eintracht Frankfurt · Forsvar' },
  { name: 'Koni De Winter', team: 'BEL', flag: '🇧🇪', info: 'AC Milan · Forsvar' },
  { name: 'Brandon Mechele', team: 'BEL', flag: '🇧🇪', info: 'Club Brugge · Forsvar' },
  { name: 'Nathan Ngoy', team: 'BEL', flag: '🇧🇪', info: 'Lille · Forsvar' },
  { name: 'Thomas Meunier', team: 'BEL', flag: '🇧🇪', info: 'Lille · Forsvar' },
  { name: 'Timothy Castagne', team: 'BEL', flag: '🇧🇪', info: 'Fulham · Forsvar' },
  { name: 'Maxim De Cuyper', team: 'BEL', flag: '🇧🇪', info: 'Brighton · Forsvar' },
  { name: 'Joaquin Seys', team: 'BEL', flag: '🇧🇪', info: 'Club Brugge · Forsvar' },
  { name: 'Kevin De Bruyne', team: 'BEL', flag: '🇧🇪', info: 'Napoli · Midtbane · Kaptein' },
  { name: 'Amadou Onana', team: 'BEL', flag: '🇧🇪', info: 'Aston Villa · Midtbane' },
  { name: 'Youri Tielemans', team: 'BEL', flag: '🇧🇪', info: 'Aston Villa · Midtbane' },
  { name: 'Hans Vanaken', team: 'BEL', flag: '🇧🇪', info: 'Club Brugge · Midtbane' },
  { name: 'Nicolas Raskin', team: 'BEL', flag: '🇧🇪', info: 'Rangers · Midtbane' },
  { name: 'Axel Witsel', team: 'BEL', flag: '🇧🇪', info: 'Girona · Midtbane' },
  { name: 'Jeremy Doku', team: 'BEL', flag: '🇧🇪', info: 'Manchester City · Angrep' },
  { name: 'Leandro Trossard', team: 'BEL', flag: '🇧🇪', info: 'Arsenal · Angrep' },
  { name: 'Alexis Saelemaekers', team: 'BEL', flag: '🇧🇪', info: 'AC Milan · Angrep' },
  { name: 'Dodi Lukebakio', team: 'BEL', flag: '🇧🇪', info: 'Benfica · Angrep' },
  { name: 'Romelu Lukaku', team: 'BEL', flag: '🇧🇪', info: 'Napoli · Spiss' },
  { name: 'Charles De Ketelaere', team: 'BEL', flag: '🇧🇪', info: 'Atalanta · Angrep' },
  { name: 'Mathias Fernandez-Pardo', team: 'BEL', flag: '🇧🇪', info: 'Lille · Angrep' },
  { name: 'Diego Moreira', team: 'BEL', flag: '🇧🇪', info: 'Strasbourg · Angrep' },
  // USA (D)
  { name: 'Christian Pulisic', team: 'USA', flag: '🇺🇸', info: 'AC Milan' },
  { name: 'Gio Reyna', team: 'USA', flag: '🇺🇸', info: 'Nottingham Forest' },
  { name: 'Ricardo Pepi', team: 'USA', flag: '🇺🇸', info: 'PSV Eindhoven' },
  { name: 'Weston McKennie', team: 'USA', flag: '🇺🇸', info: 'Juventus' },
  { name: 'Folarin Balogun', team: 'USA', flag: '🇺🇸', info: 'Monaco' },
  { name: 'Timothy Weah', team: 'USA', flag: '🇺🇸', info: 'Juventus' },
  // Mexico (A)
  { name: 'Hirving Lozano', team: 'MEX', flag: '🇲🇽', info: 'PSV Eindhoven' },
  { name: 'Raúl Jiménez', team: 'MEX', flag: '🇲🇽', info: 'Fulham' },
  { name: 'Henry Martín', team: 'MEX', flag: '🇲🇽', info: 'Club América' },
  { name: 'Edson Álvarez', team: 'MEX', flag: '🇲🇽', info: 'West Ham' },
  // Japan (F) – komplett VM-tropp 2026
  { name: 'Zion Suzuki', team: 'JPN', flag: '🇯🇵', info: 'Parma · Keeper' },
  { name: 'Keisuke Osako', team: 'JPN', flag: '🇯🇵', info: 'Sanfrecce Hiroshima · Keeper' },
  { name: 'Tomoki Hayakawa', team: 'JPN', flag: '🇯🇵', info: 'Kashima Antlers · Keeper' },
  { name: 'Yuta Nagatomo', team: 'JPN', flag: '🇯🇵', info: 'FC Tokyo · Forsvar' },
  { name: 'Shogo Taniguchi', team: 'JPN', flag: '🇯🇵', info: 'Sint-Truiden · Forsvar' },
  { name: 'Ko Itakura', team: 'JPN', flag: '🇯🇵', info: 'Ajax · Forsvar' },
  { name: 'Tsuyoshi Watanabe', team: 'JPN', flag: '🇯🇵', info: 'Feyenoord · Forsvar' },
  { name: 'Takehiro Tomiyasu', team: 'JPN', flag: '🇯🇵', info: 'Ajax · Forsvar' },
  { name: 'Hiroki Ito', team: 'JPN', flag: '🇯🇵', info: 'Bayern München · Forsvar' },
  { name: 'Ayumu Seko', team: 'JPN', flag: '🇯🇵', info: 'Le Havre · Forsvar' },
  { name: 'Yukinari Sugawara', team: 'JPN', flag: '🇯🇵', info: 'Werder Bremen · Forsvar' },
  { name: 'Junnosuke Suzuki', team: 'JPN', flag: '🇯🇵', info: 'FC København · Midtbane' },
  { name: 'Wataru Endo', team: 'JPN', flag: '🇯🇵', info: 'Liverpool · Midtbane' },
  { name: 'Junya Ito', team: 'JPN', flag: '🇯🇵', info: 'Genk · Midtbane' },
  { name: 'Daichi Kamada', team: 'JPN', flag: '🇯🇵', info: 'Crystal Palace · Midtbane' },
  { name: 'Ritsu Doan', team: 'JPN', flag: '🇯🇵', info: 'Eintracht Frankfurt · Midtbane' },
  { name: 'Ao Tanaka', team: 'JPN', flag: '🇯🇵', info: 'Leeds · Midtbane' },
  { name: 'Keito Nakamura', team: 'JPN', flag: '🇯🇵', info: 'Reims · Midtbane' },
  { name: 'Kaishu Sano', team: 'JPN', flag: '🇯🇵', info: 'Mainz · Midtbane' },
  { name: 'Takefusa Kubo', team: 'JPN', flag: '🇯🇵', info: 'Real Sociedad · Midtbane' },
  { name: 'Yuito Suzuki', team: 'JPN', flag: '🇯🇵', info: 'Freiburg · Midtbane' },
  { name: 'Koki Ogawa', team: 'JPN', flag: '🇯🇵', info: 'NEC Nijmegen · Angrep' },
  { name: 'Daizen Maeda', team: 'JPN', flag: '🇯🇵', info: 'Celtic · Angrep' },
  { name: 'Ayase Ueda', team: 'JPN', flag: '🇯🇵', info: 'Feyenoord · Spiss' },
  { name: 'Kento Shiogai', team: 'JPN', flag: '🇯🇵', info: 'VfL Wolfsburg · Angrep' },
  { name: 'Keisuke Goto', team: 'JPN', flag: '🇯🇵', info: 'Sint-Truiden · Angrep' },
  // Marokko (C)
  { name: 'Hakim Ziyech', team: 'MAR', flag: '🇲🇦', info: 'Galatasaray' },
  { name: 'Achraf Hakimi', team: 'MAR', flag: '🇲🇦', info: 'Paris Saint-Germain' },
  { name: 'Youssef En-Nesyri', team: 'MAR', flag: '🇲🇦', info: 'Fenerbahçe' },
  { name: 'Sofiane Boufal', team: 'MAR', flag: '🇲🇦', info: 'Angers' },
  // Senegal (I)
  { name: 'Sadio Mané', team: 'SEN', flag: '🇸🇳', info: 'Al Nassr' },
  { name: 'Ismaïla Sarr', team: 'SEN', flag: '🇸🇳', info: 'Crystal Palace' },
  { name: 'Iliman Ndiaye', team: 'SEN', flag: '🇸🇳', info: 'Everton' },
  // Uruguay (H)
  { name: 'Darwin Núñez', team: 'URU', flag: '🇺🇾', info: 'Liverpool' },
  { name: 'Federico Valverde', team: 'URU', flag: '🇺🇾', info: 'Real Madrid' },
  { name: 'Luis Suárez', team: 'URU', flag: '🇺🇾', info: 'Internacional' },
  { name: 'Facundo Pellistri', team: 'URU', flag: '🇺🇾', info: 'Manchester United' },
  // Colombia (K)
  { name: 'Luis Díaz', team: 'COL', flag: '🇨🇴', info: 'Liverpool' },
  { name: 'James Rodríguez', team: 'COL', flag: '🇨🇴', info: 'Rayo Vallecano' },
  { name: 'Jhon Durán', team: 'COL', flag: '🇨🇴', info: 'Aston Villa' },
  { name: 'Cucho Hernández', team: 'COL', flag: '🇨🇴', info: 'Columbus Crew' },
  // Ecuador (E)
  { name: 'Moisés Caicedo', team: 'ECU', flag: '🇪🇨', info: 'Chelsea' },
  { name: 'Enner Valencia', team: 'ECU', flag: '🇪🇨', info: 'Internacional' },
  { name: 'Jeremy Sarmiento', team: 'ECU', flag: '🇪🇨', info: 'Brighton' },
  // Australia (D)
  { name: 'Mat Ryan', team: 'AUS', flag: '🇦🇺', info: 'Real Sociedad' },
  { name: 'Mitchell Duke', team: 'AUS', flag: '🇦🇺', info: 'Macarthur FC' },
  { name: 'Martin Boyle', team: 'AUS', flag: '🇦🇺', info: 'Panathinaikos' },
  // Kroatia (L) – komplett VM-tropp 2026
  { name: 'Dominik Livaković', team: 'CRO', flag: '🇭🇷', info: 'Dinamo Zagreb · Keeper' },
  { name: 'Dominik Kotarski', team: 'CRO', flag: '🇭🇷', info: 'FC København · Keeper' },
  { name: 'Ivor Pandur', team: 'CRO', flag: '🇭🇷', info: 'Hull · Keeper' },
  { name: 'Joško Gvardiol', team: 'CRO', flag: '🇭🇷', info: 'Manchester City · Forsvar' },
  { name: 'Duje Ćaleta-Car', team: 'CRO', flag: '🇭🇷', info: 'Real Sociedad · Forsvar' },
  { name: 'Josip Šutalo', team: 'CRO', flag: '🇭🇷', info: 'Ajax · Forsvar' },
  { name: 'Josip Stanišić', team: 'CRO', flag: '🇭🇷', info: 'Bayern München · Forsvar' },
  { name: 'Marin Pongračić', team: 'CRO', flag: '🇭🇷', info: 'Fiorentina · Forsvar' },
  { name: 'Martin Erlić', team: 'CRO', flag: '🇭🇷', info: 'Midtjylland · Forsvar' },
  { name: 'Luka Vušković', team: 'CRO', flag: '🇭🇷', info: 'HSV · Forsvar' },
  { name: 'Luka Modrić', team: 'CRO', flag: '🇭🇷', info: 'AC Milan · Midtbane · Kaptein' },
  { name: 'Mateo Kovačić', team: 'CRO', flag: '🇭🇷', info: 'Manchester City · Midtbane' },
  { name: 'Mario Pašalić', team: 'CRO', flag: '🇭🇷', info: 'Atalanta · Midtbane' },
  { name: 'Nikola Vlašić', team: 'CRO', flag: '🇭🇷', info: 'Torino · Midtbane' },
  { name: 'Luka Sučić', team: 'CRO', flag: '🇭🇷', info: 'Real Sociedad · Midtbane' },
  { name: 'Martin Baturina', team: 'CRO', flag: '🇭🇷', info: 'Como · Midtbane' },
  { name: 'Kristijan Jakić', team: 'CRO', flag: '🇭🇷', info: 'Augsburg · Midtbane' },
  { name: 'Petar Sučić', team: 'CRO', flag: '🇭🇷', info: 'Inter · Midtbane' },
  { name: 'Nikola Moro', team: 'CRO', flag: '🇭🇷', info: 'Bologna · Midtbane' },
  { name: 'Toni Fruk', team: 'CRO', flag: '🇭🇷', info: 'Rijeka · Midtbane' },
  { name: 'Ivan Perišić', team: 'CRO', flag: '🇭🇷', info: 'PSV · Angrep' },
  { name: 'Andrej Kramarić', team: 'CRO', flag: '🇭🇷', info: 'Hoffenheim · Angrep' },
  { name: 'Ante Budimir', team: 'CRO', flag: '🇭🇷', info: 'Osasuna · Spiss' },
  { name: 'Marko Pašalić', team: 'CRO', flag: '🇭🇷', info: 'Orlando · Angrep' },
  { name: 'Petar Musa', team: 'CRO', flag: '🇭🇷', info: 'Dallas · Spiss' },
  { name: 'Igor Matanović', team: 'CRO', flag: '🇭🇷', info: 'Freiburg · Angrep' },
  // Sveits (B)
  { name: 'Granit Xhaka', team: 'SUI', flag: '🇨🇭', info: 'Bayer Leverkusen' },
  { name: 'Xherdan Shaqiri', team: 'SUI', flag: '🇨🇭', info: 'Chicago Fire' },
  { name: 'Breel Embolo', team: 'SUI', flag: '🇨🇭', info: 'Monaco' },
  { name: 'Ruben Vargas', team: 'SUI', flag: '🇨🇭', info: 'Augsburg' },
  // Tyrkia (D)
  { name: 'Hakan Çalhanoğlu', team: 'TUR', flag: '🇹🇷', info: 'Inter' },
  { name: 'Arda Güler', team: 'TUR', flag: '🇹🇷', info: 'Real Madrid' },
  { name: 'Kerem Aktürkoğlu', team: 'TUR', flag: '🇹🇷', info: 'Galatasaray' },
  { name: 'Cenk Tosun', team: 'TUR', flag: '🇹🇷', info: 'Beşiktaş' },
  // Canada (B)
  { name: 'Alphonso Davies', team: 'CAN', flag: '🇨🇦', info: 'Bayern München' },
  { name: 'Jonathan David', team: 'CAN', flag: '🇨🇦', info: 'Lille' },
  { name: 'Cyle Larin', team: 'CAN', flag: '🇨🇦', info: 'Club Brugge' },
  { name: 'Tajon Buchanan', team: 'CAN', flag: '🇨🇦', info: 'Inter' },
  // Sør-Korea (A) – komplett VM-tropp 2026
  { name: 'Jo Hyun-woo', team: 'KOR', flag: '🇰🇷', info: 'Ulsan HD · Keeper' },
  { name: 'Kim Seung-gyu', team: 'KOR', flag: '🇰🇷', info: 'FC Tokyo · Keeper' },
  { name: 'Song Bum-keun', team: 'KOR', flag: '🇰🇷', info: 'Jeonbuk Hyundai · Keeper' },
  { name: 'Kim Min-jae', team: 'KOR', flag: '🇰🇷', info: 'Bayern München · Forsvar' },
  { name: 'Jo Yu-min', team: 'KOR', flag: '🇰🇷', info: 'Sharjah · Forsvar' },
  { name: 'Lee Han-beom', team: 'KOR', flag: '🇰🇷', info: 'Midtjylland · Forsvar' },
  { name: 'Kim Tae-hyun', team: 'KOR', flag: '🇰🇷', info: 'Kashima Antlers · Forsvar' },
  { name: 'Park Jin-seop', team: 'KOR', flag: '🇰🇷', info: 'Zhejiang FC · Forsvar' },
  { name: 'Lee Ki-hyeok', team: 'KOR', flag: '🇰🇷', info: 'Gangwon FC · Forsvar' },
  { name: 'Lee Tae-seok', team: 'KOR', flag: '🇰🇷', info: 'Austria Wien · Forsvar' },
  { name: 'Seol Young-woo', team: 'KOR', flag: '🇰🇷', info: 'Røde Stjerne · Forsvar' },
  { name: 'Jens Castrop', team: 'KOR', flag: '🇰🇷', info: 'Borussia Mönchengladbach · Forsvar' },
  { name: 'Kim Moon-hwan', team: 'KOR', flag: '🇰🇷', info: 'Daejeon Hana · Forsvar' },
  { name: 'Yang Hyun-jun', team: 'KOR', flag: '🇰🇷', info: 'Celtic · Midtbane' },
  { name: 'Paik Seung-ho', team: 'KOR', flag: '🇰🇷', info: 'Birmingham · Midtbane' },
  { name: 'Hwang In-beom', team: 'KOR', flag: '🇰🇷', info: 'Feyenoord · Midtbane' },
  { name: 'Kim Jin-kyu', team: 'KOR', flag: '🇰🇷', info: 'Jeonbuk Hyundai · Midtbane' },
  { name: 'Bae Jun-ho', team: 'KOR', flag: '🇰🇷', info: 'Stoke City · Midtbane' },
  { name: 'Um Ji-sung', team: 'KOR', flag: '🇰🇷', info: 'Swansea City · Midtbane' },
  { name: 'Hwang Hee-chan', team: 'KOR', flag: '🇰🇷', info: 'Wolverhampton · Midtbane' },
  { name: 'Lee Dong-gyeong', team: 'KOR', flag: '🇰🇷', info: 'Ulsan HD · Midtbane' },
  { name: 'Lee Jae-sung', team: 'KOR', flag: '🇰🇷', info: 'Mainz · Midtbane' },
  { name: 'Lee Kang-in', team: 'KOR', flag: '🇰🇷', info: 'Paris Saint-Germain · Midtbane' },
  { name: 'Oh Hyun-kyu', team: 'KOR', flag: '🇰🇷', info: 'Beşiktaş · Angrep' },
  { name: 'Son Heung-min', team: 'KOR', flag: '🇰🇷', info: 'LA FC · Angrep · Kaptein' },
  { name: 'Cho Kyu-sung', team: 'KOR', flag: '🇰🇷', info: 'Midtjylland · Angrep' },
  // Ghana (L)
  { name: 'Jordan Ayew', team: 'GHA', flag: '🇬🇭', info: 'Leicester City' },
  { name: 'André Ayew', team: 'GHA', flag: '🇬🇭', info: 'Le Havre' },
  { name: 'Mohammed Kudus', team: 'GHA', flag: '🇬🇭', info: 'West Ham' },
  // Østerrike (J) – komplett VM-tropp 2026
  { name: 'Patrick Pentz', team: 'AUT', flag: '🇦🇹', info: 'Brøndby · Keeper' },
  { name: 'Alexander Schlager', team: 'AUT', flag: '🇦🇹', info: 'Red Bull Salzburg · Keeper' },
  { name: 'Florian Wiegele', team: 'AUT', flag: '🇦🇹', info: 'Viktoria Plzeň · Keeper' },
  { name: 'David Affengruber', team: 'AUT', flag: '🇦🇹', info: 'Elche · Forsvar' },
  { name: 'David Alaba', team: 'AUT', flag: '🇦🇹', info: 'Real Madrid · Forsvar' },
  { name: 'Kevin Danso', team: 'AUT', flag: '🇦🇹', info: 'Tottenham · Forsvar' },
  { name: 'Marco Friedl', team: 'AUT', flag: '🇦🇹', info: 'Werder Bremen · Forsvar' },
  { name: 'Philipp Lienhart', team: 'AUT', flag: '🇦🇹', info: 'SC Freiburg · Forsvar' },
  { name: 'Phillipp Mwene', team: 'AUT', flag: '🇦🇹', info: 'Mainz 05 · Forsvar' },
  { name: 'Stefan Posch', team: 'AUT', flag: '🇦🇹', info: 'Mainz 05 · Forsvar' },
  { name: 'Alexander Prass', team: 'AUT', flag: '🇦🇹', info: 'TSG Hoffenheim · Forsvar' },
  { name: 'Michael Svoboda', team: 'AUT', flag: '🇦🇹', info: 'Venezia · Forsvar' },
  { name: 'Christoph Baumgartner', team: 'AUT', flag: '🇦🇹', info: 'RB Leipzig · Midtbane' },
  { name: 'Carney Chukwuemeka', team: 'AUT', flag: '🇦🇹', info: 'Borussia Dortmund · Midtbane' },
  { name: 'Florian Grillitsch', team: 'AUT', flag: '🇦🇹', info: 'Braga · Midtbane' },
  { name: 'Konrad Laimer', team: 'AUT', flag: '🇦🇹', info: 'Bayern München · Midtbane' },
  { name: 'Marcel Sabitzer', team: 'AUT', flag: '🇦🇹', info: 'Borussia Dortmund · Midtbane' },
  { name: 'Xaver Schlager', team: 'AUT', flag: '🇦🇹', info: 'RB Leipzig · Midtbane' },
  { name: 'Romano Schmid', team: 'AUT', flag: '🇦🇹', info: 'Werder Bremen · Midtbane' },
  { name: 'Alessandro Schöpf', team: 'AUT', flag: '🇦🇹', info: 'Wolfsberger AC · Midtbane' },
  { name: 'Nicolas Seiwald', team: 'AUT', flag: '🇦🇹', info: 'RB Leipzig · Midtbane' },
  { name: 'Paul Wanner', team: 'AUT', flag: '🇦🇹', info: 'PSV Eindhoven · Midtbane' },
  { name: 'Patrick Wimmer', team: 'AUT', flag: '🇦🇹', info: 'VfL Wolfsburg · Midtbane' },
  { name: 'Marko Arnautović', team: 'AUT', flag: '🇦🇹', info: 'Røde Stjerne Beograd · Spiss' },
  { name: 'Michael Gregoritsch', team: 'AUT', flag: '🇦🇹', info: 'Augsburg · Spiss' },
  { name: 'Saša Kalajdžić', team: 'AUT', flag: '🇦🇹', info: 'LASK · Spiss' },
  // Sverige (F) – komplett VM-tropp 2026
  { name: 'Viktor Johansson', team: 'SWE', flag: '🇸🇪', info: 'Stoke City · Keeper' },
  { name: 'Kristoffer Nordfeldt', team: 'SWE', flag: '🇸🇪', info: 'AIK · Keeper' },
  { name: 'Jacob Widell Zetterström', team: 'SWE', flag: '🇸🇪', info: 'Derby County · Keeper' },
  { name: 'Hjalmar Ekdal', team: 'SWE', flag: '🇸🇪', info: 'Burnley · Forsvar' },
  { name: 'Gabriel Gudmundsson', team: 'SWE', flag: '🇸🇪', info: 'Leeds United · Forsvar' },
  { name: 'Isak Hien', team: 'SWE', flag: '🇸🇪', info: 'Atalanta · Forsvar' },
  { name: 'Emil Holm', team: 'SWE', flag: '🇸🇪', info: 'Juventus · Forsvar' },
  { name: 'Gustaf Lagerbielke', team: 'SWE', flag: '🇸🇪', info: 'Braga · Forsvar' },
  { name: 'Victor Lindelöf', team: 'SWE', flag: '🇸🇪', info: 'Aston Villa · Forsvar' },
  { name: 'Erik Smith', team: 'SWE', flag: '🇸🇪', info: 'St. Pauli · Forsvar' },
  { name: 'Carl Starfelt', team: 'SWE', flag: '🇸🇪', info: 'Celta Vigo · Forsvar' },
  { name: 'Elliot Stroud', team: 'SWE', flag: '🇸🇪', info: 'Mjällby · Forsvar' },
  { name: 'Daniel Svensson', team: 'SWE', flag: '🇸🇪', info: 'Borussia Dortmund · Forsvar' },
  { name: 'Taha Ali', team: 'SWE', flag: '🇸🇪', info: 'Malmö · Midtbane' },
  { name: 'Yasin Ayari', team: 'SWE', flag: '🇸🇪', info: 'Brighton · Midtbane' },
  { name: 'Lucas Bergvall', team: 'SWE', flag: '🇸🇪', info: 'Tottenham · Midtbane' },
  { name: 'Jesper Karlström', team: 'SWE', flag: '🇸🇪', info: 'Udinese · Midtbane' },
  { name: 'Ken Sema', team: 'SWE', flag: '🇸🇪', info: 'Pafos · Midtbane' },
  { name: 'Mattias Svanberg', team: 'SWE', flag: '🇸🇪', info: 'Wolfsburg · Midtbane' },
  { name: 'Besfort Zeneli', team: 'SWE', flag: '🇸🇪', info: 'Union Saint-Gilloise · Midtbane' },
  { name: 'Alexander Bernhardsson', team: 'SWE', flag: '🇸🇪', info: 'Holstein Kiel · Angrep' },
  { name: 'Anthony Elanga', team: 'SWE', flag: '🇸🇪', info: 'Newcastle · Angrep' },
  { name: 'Viktor Gyökeres', team: 'SWE', flag: '🇸🇪', info: 'Arsenal · Spiss' },
  { name: 'Alexander Isak', team: 'SWE', flag: '🇸🇪', info: 'Liverpool · Spiss' },
  { name: 'Gustaf Nilsson', team: 'SWE', flag: '🇸🇪', info: 'Club Brugge · Spiss' },
  { name: 'Benjamin Nygren', team: 'SWE', flag: '🇸🇪', info: 'Celtic · Angrep' },
  // Saudi-Arabia (H)
  { name: 'Salem Al-Dawsari', team: 'KSA', flag: '🇸🇦', info: 'Al-Hilal' },
  { name: 'Mohammed Al-Owais', team: 'KSA', flag: '🇸🇦', info: 'Al-Hilal' },
  // Egypt (G)
  { name: 'Mohamed Salah', team: 'EGY', flag: '🇪🇬', info: 'Liverpool' },
  { name: 'Trezeguet', team: 'EGY', flag: '🇪🇬', info: 'Trabzonspor' },
  // Iran (G)
  { name: 'Mehdi Taremi', team: 'IRN', flag: '🇮🇷', info: 'Inter' },
  { name: 'Sardar Azmoun', team: 'IRN', flag: '🇮🇷', info: 'Roma' },
  // Skottland (C)
  { name: 'Scott McTominay', team: 'SCO', flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', info: 'Napoli' },
  { name: 'Andy Robertson', team: 'SCO', flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', info: 'Liverpool' },
  { name: 'Che Adams', team: 'SCO', flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', info: 'Torino' },
  // ── Lag tilføyd fra VG-troppene 14.–18. mai 2026 ───────────────────────────
  // Bosnia-Hercegovina (B) – komplett VM-tropp
  { name: 'Nikola Vasilj', team: 'BIH', flag: '🇧🇦', info: 'St. Pauli · Keeper' },
  { name: 'Martin Zlomislić', team: 'BIH', flag: '🇧🇦', info: 'Rijeka · Keeper' },
  { name: 'Osman Hadžikić', team: 'BIH', flag: '🇧🇦', info: 'Slaven Belupo · Keeper' },
  { name: 'Sead Kolašinac', team: 'BIH', flag: '🇧🇦', info: 'Atalanta · Forsvar' },
  { name: 'Amar Dedić', team: 'BIH', flag: '🇧🇦', info: 'Benfica · Forsvar' },
  { name: 'Nihad Mujakić', team: 'BIH', flag: '🇧🇦', info: 'Gaziantep · Forsvar' },
  { name: 'Nikola Katić', team: 'BIH', flag: '🇧🇦', info: 'Schalke 04 · Forsvar' },
  { name: 'Tarik Muharemović', team: 'BIH', flag: '🇧🇦', info: 'Sassuolo · Forsvar' },
  { name: 'Stjepan Radeljić', team: 'BIH', flag: '🇧🇦', info: 'Rijeka · Forsvar' },
  { name: 'Dennis Hadžikadunić', team: 'BIH', flag: '🇧🇦', info: 'Sampdoria · Forsvar' },
  { name: 'Nidal Celik', team: 'BIH', flag: '🇧🇦', info: 'Lens · Forsvar' },
  { name: 'Amir Hadžiahmetović', team: 'BIH', flag: '🇧🇦', info: 'Hull City · Midtbane' },
  { name: 'Ivan Šunjić', team: 'BIH', flag: '🇧🇦', info: 'Pafos · Midtbane' },
  { name: 'Ivan Bašić', team: 'BIH', flag: '🇧🇦', info: 'Astana · Midtbane' },
  { name: 'Dženis Burnić', team: 'BIH', flag: '🇧🇦', info: 'Karlsruher SC · Midtbane' },
  { name: 'Ermin Mahmić', team: 'BIH', flag: '🇧🇦', info: 'Slovan Liberec · Midtbane' },
  { name: 'Benjamin Tahirović', team: 'BIH', flag: '🇧🇦', info: 'Brøndby · Midtbane' },
  { name: 'Amar Memić', team: 'BIH', flag: '🇧🇦', info: 'Viktoria Plzeň · Midtbane' },
  { name: 'Armin Gigović', team: 'BIH', flag: '🇧🇦', info: 'Young Boys · Midtbane' },
  { name: 'Kerim Alajbegović', team: 'BIH', flag: '🇧🇦', info: 'RB Salzburg · Midtbane' },
  { name: 'Esmir Bajraktarević', team: 'BIH', flag: '🇧🇦', info: 'PSV · Midtbane' },
  { name: 'Ermedin Demirović', team: 'BIH', flag: '🇧🇦', info: 'VfB Stuttgart · Spiss' },
  { name: 'Jovo Lukić', team: 'BIH', flag: '🇧🇦', info: 'Cluj · Angrep' },
  { name: 'Samed Baždar', team: 'BIH', flag: '🇧🇦', info: 'Jagiellonia · Angrep' },
  { name: 'Haris Tabaković', team: 'BIH', flag: '🇧🇦', info: 'Borussia Mönchengladbach · Spiss' },
  { name: 'Edin Džeko', team: 'BIH', flag: '🇧🇦', info: 'Schalke 04 · Spiss · Kaptein' },

  // Haiti (C) – komplett VM-tropp
  { name: 'Johny Placide', team: 'HAI', flag: '🇭🇹', info: 'Bastia · Keeper' },
  { name: 'Alexandre Pierre', team: 'HAI', flag: '🇭🇹', info: 'Sochaux · Keeper' },
  { name: 'Josué Duverger', team: 'HAI', flag: '🇭🇹', info: 'Cosmos Koblenz · Keeper' },
  { name: 'Carlens Arcus', team: 'HAI', flag: '🇭🇹', info: 'Angers · Forsvar' },
  { name: 'Vilguens Paugain', team: 'HAI', flag: '🇭🇹', info: 'Zulte Waregem · Forsvar' },
  { name: 'Duke Lacroix', team: 'HAI', flag: '🇭🇹', info: 'Colorado Springs · Forsvar' },
  { name: 'Martin Experience', team: 'HAI', flag: '🇭🇹', info: 'Nancy · Forsvar' },
  { name: 'Jean-Kévin Duverne', team: 'HAI', flag: '🇭🇹', info: 'Gent · Forsvar' },
  { name: 'Ricardo Adé', team: 'HAI', flag: '🇭🇹', info: 'LDU Quito · Forsvar' },
  { name: 'Hannes Delcroix', team: 'HAI', flag: '🇭🇹', info: 'Lugano · Forsvar' },
  { name: 'Keeto Thermoncy', team: 'HAI', flag: '🇭🇹', info: 'Young Boys · Forsvar' },
  { name: 'Carl Fred Sainte', team: 'HAI', flag: '🇭🇹', info: 'El Paso Locomotive · Midtbane' },
  { name: 'Leverton Pierre', team: 'HAI', flag: '🇭🇹', info: 'Vizela · Midtbane' },
  { name: 'Danley Jean Jacques', team: 'HAI', flag: '🇭🇹', info: 'Philadelphia Union · Midtbane' },
  { name: 'Jean-Ricner Bellegarde', team: 'HAI', flag: '🇭🇹', info: 'Wolverhampton · Midtbane' },
  { name: 'Woodensky Pierre', team: 'HAI', flag: '🇭🇹', info: 'Violette · Midtbane' },
  { name: 'Dominique Simon', team: 'HAI', flag: '🇭🇹', info: 'Tatran Prešov · Midtbane' },
  { name: 'Don Deedson Loucius', team: 'HAI', flag: '🇭🇹', info: 'Dallas · Angrep' },
  { name: 'Josué Casimir', team: 'HAI', flag: '🇭🇹', info: 'Auxerre · Angrep' },
  { name: 'Derrick Etienne', team: 'HAI', flag: '🇭🇹', info: 'Toronto · Angrep' },
  { name: 'Ruben Providence', team: 'HAI', flag: '🇭🇹', info: 'Almere · Angrep' },
  { name: 'Duckens Nazon', team: 'HAI', flag: '🇭🇹', info: 'Esteghlal · Angrep' },
  { name: 'Frantzdy Pierrot', team: 'HAI', flag: '🇭🇹', info: 'Çaykur Rizespor · Spiss' },
  { name: 'Wilson Isidor', team: 'HAI', flag: '🇭🇹', info: 'Sunderland · Spiss' },
  { name: 'Yassin Fortuné', team: 'HAI', flag: '🇭🇹', info: 'Vizela · Angrep' },
  { name: 'Lenny Joseph', team: 'HAI', flag: '🇭🇹', info: 'Ferencvaros · Angrep' },

  // Curaçao (E) – komplett VM-tropp
  { name: 'Tyrick Bodak', team: 'CUW', flag: '🇨🇼', info: 'Telstar · Keeper' },
  { name: 'Trevor Doornbusch', team: 'CUW', flag: '🇨🇼', info: 'VVV-Venlo · Keeper' },
  { name: 'Eloy Room', team: 'CUW', flag: '🇨🇼', info: 'Miami FC · Keeper' },
  { name: 'Riechedly Bazoer', team: 'CUW', flag: '🇨🇼', info: 'Konyaspor · Forsvar' },
  { name: 'Joshua Brenet', team: 'CUW', flag: '🇨🇼', info: 'Kayserispor · Forsvar' },
  { name: 'Roshon van Eijma', team: 'CUW', flag: '🇨🇼', info: 'RKC Waalwijk · Forsvar' },
  { name: 'Sherel Floranus', team: 'CUW', flag: '🇨🇼', info: 'PEC Zwolle · Forsvar' },
  { name: 'Deveron Fonville', team: 'CUW', flag: '🇨🇼', info: 'NEC Nijmegen · Forsvar' },
  { name: 'Juriën Gaari', team: 'CUW', flag: '🇨🇼', info: 'Abha · Forsvar' },
  { name: 'Armando Obispo', team: 'CUW', flag: '🇨🇼', info: 'PSV Eindhoven · Forsvar' },
  { name: 'Shurandy Sambo', team: 'CUW', flag: '🇨🇼', info: 'Sparta Rotterdam · Forsvar' },
  { name: 'Juninho Bacuna', team: 'CUW', flag: '🇨🇼', info: 'FC Volendam · Midtbane' },
  { name: 'Leandro Bacuna', team: 'CUW', flag: '🇨🇼', info: 'Iğdır FK · Midtbane' },
  { name: 'Livano Comenencia', team: 'CUW', flag: '🇨🇼', info: 'FC Zürich · Midtbane' },
  { name: 'Kevin Felida', team: 'CUW', flag: '🇨🇼', info: 'FC Den Bosch · Midtbane' },
  { name: "Ar'jany Martha", team: 'CUW', flag: '🇨🇼', info: 'Rotherham United · Midtbane' },
  { name: 'Tyrese Noslin', team: 'CUW', flag: '🇨🇼', info: 'Telstar · Midtbane' },
  { name: 'Godfried Roemeratoe', team: 'CUW', flag: '🇨🇼', info: 'RKC Waalwijk · Midtbane' },
  { name: 'Jeremy Antonisse', team: 'CUW', flag: '🇨🇼', info: 'AE Kifisia · Angrep' },
  { name: 'Tahith Chong', team: 'CUW', flag: '🇨🇼', info: 'Sheffield United · Angrep' },
  { name: 'Kenji Gorré', team: 'CUW', flag: '🇨🇼', info: 'Maccabi Haifa · Angrep' },
  { name: 'Sontje Hansen', team: 'CUW', flag: '🇨🇼', info: 'Middlesbrough · Angrep' },
  { name: 'Gervane Kastaneer', team: 'CUW', flag: '🇨🇼', info: 'Terengganu FC · Angrep' },
  { name: 'Brandley Kuwas', team: 'CUW', flag: '🇨🇼', info: 'FC Volendam · Angrep' },
  { name: 'Jürgen Locadia', team: 'CUW', flag: '🇨🇼', info: 'Miami FC · Spiss' },
  { name: 'Jearl Margaritha', team: 'CUW', flag: '🇨🇼', info: 'SK Beveren · Angrep' },

  // Elfenbenskysten (E) – komplett VM-tropp
  { name: 'Yahia Fofana', team: 'CIV', flag: '🇨🇮', info: 'Rizespor · Keeper' },
  { name: 'Mohamed Koné', team: 'CIV', flag: '🇨🇮', info: 'Charleroi · Keeper' },
  { name: 'Alban Lafont', team: 'CIV', flag: '🇨🇮', info: 'Panathinaikos · Keeper' },
  { name: 'Emmanuel Agbadou', team: 'CIV', flag: '🇨🇮', info: 'Beşiktaş · Forsvar' },
  { name: 'Clément Akpa', team: 'CIV', flag: '🇨🇮', info: 'Auxerre · Forsvar' },
  { name: 'Ousmane Diomandé', team: 'CIV', flag: '🇨🇮', info: 'Sporting CP · Forsvar' },
  { name: 'Guéla Doué', team: 'CIV', flag: '🇨🇮', info: 'Strasbourg · Forsvar' },
  { name: 'Ghislain Konan', team: 'CIV', flag: '🇨🇮', info: 'Gil Vicente · Forsvar' },
  { name: 'Odilon Kossounou', team: 'CIV', flag: '🇨🇮', info: 'Atalanta · Forsvar' },
  { name: 'Evan Ndicka', team: 'CIV', flag: '🇨🇮', info: 'Roma · Forsvar' },
  { name: 'Wilfried Singo', team: 'CIV', flag: '🇨🇮', info: 'Galatasaray · Forsvar' },
  { name: 'Seko Fofana', team: 'CIV', flag: '🇨🇮', info: 'Porto · Midtbane' },
  { name: 'Parfait Guiagon', team: 'CIV', flag: '🇨🇮', info: 'Charleroi · Midtbane' },
  { name: 'Franck Kessié', team: 'CIV', flag: '🇨🇮', info: 'Al-Ahli · Midtbane' },
  { name: 'Christ Inao Oulai', team: 'CIV', flag: '🇨🇮', info: 'Trabzonspor · Midtbane' },
  { name: 'Ibrahim Sangaré', team: 'CIV', flag: '🇨🇮', info: 'Nottingham Forest · Midtbane' },
  { name: 'Jean Michaël Seri', team: 'CIV', flag: '🇨🇮', info: 'NK Maribor · Midtbane' },
  { name: 'Simon Adingra', team: 'CIV', flag: '🇨🇮', info: 'Monaco · Angrep' },
  { name: 'Ange-Yoan Bonny', team: 'CIV', flag: '🇨🇮', info: 'Inter · Angrep' },
  { name: 'Amad Diallo', team: 'CIV', flag: '🇨🇮', info: 'Manchester United · Angrep' },
  { name: 'Oumar Diakité', team: 'CIV', flag: '🇨🇮', info: 'Cercle Brugge · Angrep' },
  { name: 'Yan Diomande', team: 'CIV', flag: '🇨🇮', info: 'RB Leipzig · Angrep' },
  { name: 'Evann Guessand', team: 'CIV', flag: '🇨🇮', info: 'Aston Villa · Angrep' },
  { name: 'Nicolas Pépé', team: 'CIV', flag: '🇨🇮', info: 'Villarreal · Angrep' },
  { name: 'Bazoumana Touré', team: 'CIV', flag: '🇨🇮', info: 'Hoffenheim · Angrep' },
  { name: 'Elye Wahi', team: 'CIV', flag: '🇨🇮', info: 'Nice · Spiss' },

  // Tunisia (F) – komplett VM-tropp
  { name: 'Aymen Dahmen', team: 'TUN', flag: '🇹🇳', info: 'CS Sfaxien · Keeper' },
  { name: 'Sabri Ben Hassen', team: 'TUN', flag: '🇹🇳', info: 'Étoile du Sahel · Keeper' },
  { name: 'Abdelmouhib Chamakh', team: 'TUN', flag: '🇹🇳', info: 'Club Africain · Keeper' },
  { name: 'Montassar Talbi', team: 'TUN', flag: '🇹🇳', info: 'Lorient · Forsvar' },
  { name: 'Dylan Bronn', team: 'TUN', flag: '🇹🇳', info: 'Servette · Forsvar' },
  { name: 'Omar Rekik', team: 'TUN', flag: '🇹🇳', info: 'Maribor · Forsvar' },
  { name: 'Yan Valery', team: 'TUN', flag: '🇹🇳', info: 'Young Boys · Forsvar' },
  { name: 'Ali Abdi', team: 'TUN', flag: '🇹🇳', info: 'Nice · Forsvar' },
  { name: 'Moutaz Neffati', team: 'TUN', flag: '🇹🇳', info: 'IFK Norrköping · Forsvar' },
  { name: 'Raed Chikhaoui', team: 'TUN', flag: '🇹🇳', info: 'Monastir · Forsvar' },
  { name: 'Adam Arous', team: 'TUN', flag: '🇹🇳', info: 'Kasımpaşa · Forsvar' },
  { name: 'Mohamed Amine Ben Hamida', team: 'TUN', flag: '🇹🇳', info: 'Espérance de Tunis · Forsvar' },
  { name: 'Ellyes Skhiri', team: 'TUN', flag: '🇹🇳', info: 'Eintracht Frankfurt · Midtbane' },
  { name: 'Hannibal Mejbri', team: 'TUN', flag: '🇹🇳', info: 'Burnley · Midtbane' },
  { name: 'Anis Ben Slimane', team: 'TUN', flag: '🇹🇳', info: 'Norwich · Midtbane' },
  { name: 'Hadj Mahmoud', team: 'TUN', flag: '🇹🇳', info: 'Lugano · Midtbane' },
  { name: 'Rani Khedira', team: 'TUN', flag: '🇹🇳', info: 'Union Berlin · Midtbane' },
  { name: 'Mortadha Ben Ouanes', team: 'TUN', flag: '🇹🇳', info: 'Kasımpaşa · Midtbane' },
  { name: 'Elias Achouri', team: 'TUN', flag: '🇹🇳', info: 'FC København · Angrep' },
  { name: 'Ismaël Gharbi', team: 'TUN', flag: '🇹🇳', info: 'Augsburg · Angrep' },
  { name: 'Elias Saad', team: 'TUN', flag: '🇹🇳', info: 'Hannover 96 · Angrep' },
  { name: 'Sebastian Tounekti', team: 'TUN', flag: '🇹🇳', info: 'Celtic · Angrep' },
  { name: 'Firas Chaouat', team: 'TUN', flag: '🇹🇳', info: 'Club Africain · Angrep' },
  { name: 'Khalil Ayari', team: 'TUN', flag: '🇹🇳', info: 'Paris Saint-Germain · Angrep' },
  { name: 'Hazem Mastouri', team: 'TUN', flag: '🇹🇳', info: 'Dinamo Makhachkala · Angrep' },
  { name: 'Rayan Elloumi', team: 'TUN', flag: '🇹🇳', info: 'Vancouver Whitecaps · Angrep' },

  // New Zealand (G) – komplett VM-tropp
  { name: 'Max Crocombe', team: 'NZL', flag: '🇳🇿', info: 'Millwall · Keeper' },
  { name: 'Alex Paulsen', team: 'NZL', flag: '🇳🇿', info: 'Lechia Gdańsk · Keeper' },
  { name: 'Michael Woud', team: 'NZL', flag: '🇳🇿', info: 'Auckland FC · Keeper' },
  { name: 'Tim Payne', team: 'NZL', flag: '🇳🇿', info: 'Wellington Phoenix · Forsvar' },
  { name: 'Francis De Vries', team: 'NZL', flag: '🇳🇿', info: 'Auckland FC · Forsvar' },
  { name: 'Tyler Bindon', team: 'NZL', flag: '🇳🇿', info: 'Nottingham Forest · Forsvar' },
  { name: 'Michael Boxall', team: 'NZL', flag: '🇳🇿', info: 'Minnesota United · Forsvar' },
  { name: 'Liberato Cacace', team: 'NZL', flag: '🇳🇿', info: 'Wrexham · Forsvar' },
  { name: 'Nando Pijnaker', team: 'NZL', flag: '🇳🇿', info: 'Auckland FC · Forsvar' },
  { name: 'Finn Surman', team: 'NZL', flag: '🇳🇿', info: 'Portland Timbers · Forsvar' },
  { name: 'Callan Elliot', team: 'NZL', flag: '🇳🇿', info: 'Auckland FC · Forsvar' },
  { name: 'Tommy Smith', team: 'NZL', flag: '🇳🇿', info: 'Braintree Town · Forsvar' },
  { name: 'Joe Bell', team: 'NZL', flag: '🇳🇿', info: 'Viking FK · Midtbane' },
  { name: 'Matt Garbett', team: 'NZL', flag: '🇳🇿', info: 'Peterborough United · Midtbane' },
  { name: 'Marko Stamenić', team: 'NZL', flag: '🇳🇿', info: 'Swansea City · Midtbane' },
  { name: 'Sarpreet Singh', team: 'NZL', flag: '🇳🇿', info: 'Wellington Phoenix · Midtbane' },
  { name: 'Alex Rufer', team: 'NZL', flag: '🇳🇿', info: 'Wellington Phoenix · Midtbane' },
  { name: 'Ryan Thomas', team: 'NZL', flag: '🇳🇿', info: 'PEC Zwolle · Midtbane' },
  { name: 'Chris Wood', team: 'NZL', flag: '🇳🇿', info: 'Nottingham Forest · Spiss · Kaptein' },
  { name: 'Eli Just', team: 'NZL', flag: '🇳🇿', info: 'Motherwell · Angrep' },
  { name: 'Kosta Barbarouses', team: 'NZL', flag: '🇳🇿', info: 'Western Sydney Wanderers · Angrep' },
  { name: 'Ben Waine', team: 'NZL', flag: '🇳🇿', info: 'Port Vale · Angrep' },
  { name: 'Ben Old', team: 'NZL', flag: '🇳🇿', info: 'Saint-Étienne · Angrep' },
  { name: 'Callum McCowatt', team: 'NZL', flag: '🇳🇿', info: 'Silkeborg IF · Angrep' },
  { name: 'Jesse Randall', team: 'NZL', flag: '🇳🇿', info: 'Auckland FC · Angrep' },
  { name: 'Lachlan Bayliss', team: 'NZL', flag: '🇳🇿', info: 'Newcastle Jets · Angrep' },

  // Kapp Verde (H) – komplett VM-tropp
  { name: 'Carlos dos Santos', team: 'CPV', flag: '🇨🇻', info: 'San Diego · Keeper' },
  { name: 'Márcio Rosa', team: 'CPV', flag: '🇨🇻', info: 'Montana 1921 · Keeper' },
  { name: 'Vozinha', team: 'CPV', flag: '🇨🇻', info: 'Chaves · Keeper' },
  { name: 'Sidny Cabral', team: 'CPV', flag: '🇨🇻', info: 'Benfica · Forsvar' },
  { name: 'Diney Borges', team: 'CPV', flag: '🇨🇻', info: 'Al Bataeh · Forsvar' },
  { name: 'Logan Costa', team: 'CPV', flag: '🇨🇻', info: 'Villarreal · Forsvar' },
  { name: 'Roberto Lopes', team: 'CPV', flag: '🇨🇻', info: 'Shamrock Rovers · Forsvar' },
  { name: 'Steven Moreira', team: 'CPV', flag: '🇨🇻', info: 'Columbus Crew · Forsvar' },
  { name: 'Wagner Pina', team: 'CPV', flag: '🇨🇻', info: 'Trabzonspor · Forsvar' },
  { name: 'Kelvin Pires', team: 'CPV', flag: '🇨🇻', info: 'SJK Seinäjoki · Forsvar' },
  { name: 'Stopira', team: 'CPV', flag: '🇨🇻', info: 'Torreense · Forsvar' },
  { name: 'Telmo Arcanjo', team: 'CPV', flag: '🇨🇻', info: 'Vitória Guimarães · Midtbane' },
  { name: 'Deroy Duarte', team: 'CPV', flag: '🇨🇻', info: 'Ludogorets · Midtbane' },
  { name: 'Laros Duarte', team: 'CPV', flag: '🇨🇻', info: 'Puskás Akadémia · Midtbane' },
  { name: 'João Paulo Fernandes', team: 'CPV', flag: '🇨🇻', info: 'FCSB · Midtbane' },
  { name: 'Jamiro Monteiro', team: 'CPV', flag: '🇨🇻', info: 'PEC Zwolle · Midtbane' },
  { name: 'Kévin Pina', team: 'CPV', flag: '🇨🇻', info: 'Krasnodar · Midtbane' },
  { name: 'Yannick Semedo', team: 'CPV', flag: '🇨🇻', info: 'Farense · Midtbane' },
  { name: 'Gilson Benchimol', team: 'CPV', flag: '🇨🇻', info: 'Akron Togliatti · Angrep' },
  { name: 'Jovane Cabral', team: 'CPV', flag: '🇨🇻', info: 'Estrela de Amadora · Angrep' },
  { name: 'Dailon Livramento', team: 'CPV', flag: '🇨🇻', info: 'Casa Pia · Angrep' },
  { name: 'Ryan Mendes', team: 'CPV', flag: '🇨🇻', info: 'Iğdır · Angrep' },
  { name: 'Nuno da Costa', team: 'CPV', flag: '🇨🇻', info: 'İstanbul Başakşehir · Angrep' },
  { name: 'Garry Rodrigues', team: 'CPV', flag: '🇨🇻', info: 'Apollon Limassol · Angrep' },
  { name: 'Willy Semedo', team: 'CPV', flag: '🇨🇻', info: 'Omonia Nicosia · Angrep' },
  { name: 'Hélio Varela', team: 'CPV', flag: '🇨🇻', info: 'Maccabi Tel Aviv · Angrep' },

  // DR Kongo (K) – komplett VM-tropp
  { name: 'Matthieu Epolo', team: 'COD', flag: '🇨🇩', info: 'Standard Liège · Keeper' },
  { name: 'Timothy Fayulu', team: 'COD', flag: '🇨🇩', info: 'Noah · Keeper' },
  { name: 'Lionel Mpasi', team: 'COD', flag: '🇨🇩', info: 'Le Havre · Keeper' },
  { name: 'Dylan Batubinsika', team: 'COD', flag: '🇨🇩', info: 'Larisa · Forsvar' },
  { name: 'Rocky Bushiri', team: 'COD', flag: '🇨🇩', info: 'Hibernian · Forsvar' },
  { name: 'Gédéon Kalulu', team: 'COD', flag: '🇨🇩', info: 'Aris Limassol · Forsvar' },
  { name: 'Steve Kapuadi', team: 'COD', flag: '🇨🇩', info: 'Widzew Łódź · Forsvar' },
  { name: 'Joris Kayembe', team: 'COD', flag: '🇨🇩', info: 'Racing Genk · Forsvar' },
  { name: 'Arthur Masuaku', team: 'COD', flag: '🇨🇩', info: 'Racing Lens · Forsvar' },
  { name: 'Chancel Mbemba', team: 'COD', flag: '🇨🇩', info: 'Lille · Forsvar' },
  { name: 'Axel Tuanzebe', team: 'COD', flag: '🇨🇩', info: 'Burnley · Forsvar' },
  { name: 'Aaron Wan-Bissaka', team: 'COD', flag: '🇨🇩', info: 'West Ham United · Forsvar' },
  { name: 'Théo Bongonda', team: 'COD', flag: '🇨🇩', info: 'Spartak Moskva · Midtbane' },
  { name: 'Brian Cipenga', team: 'COD', flag: '🇨🇩', info: 'Castellón · Midtbane' },
  { name: 'Meshack Elia', team: 'COD', flag: '🇨🇩', info: 'Alanyaspor · Midtbane' },
  { name: 'Gaël Kakuta', team: 'COD', flag: '🇨🇩', info: 'Larisa · Midtbane' },
  { name: 'Edo Kayembe', team: 'COD', flag: '🇨🇩', info: 'Watford · Midtbane' },
  { name: 'Nathanaël Mbuku', team: 'COD', flag: '🇨🇩', info: 'Montpellier · Midtbane' },
  { name: 'Samuel Moutoussamy', team: 'COD', flag: '🇨🇩', info: 'Atromitos · Midtbane' },
  { name: "Ngal'ayel Mukau", team: 'COD', flag: '🇨🇩', info: 'Lille · Midtbane' },
  { name: 'Charles Pickel', team: 'COD', flag: '🇨🇩', info: 'Espanyol · Midtbane' },
  { name: 'Noah Sadiki', team: 'COD', flag: '🇨🇩', info: 'Sunderland · Midtbane' },
  { name: 'Cedric Bakambu', team: 'COD', flag: '🇨🇩', info: 'Real Betis · Angrep' },
  { name: 'Simon Banza', team: 'COD', flag: '🇨🇩', info: 'Al Jazira · Angrep' },
  { name: 'Fiston Mayele', team: 'COD', flag: '🇨🇩', info: 'Pyramids · Angrep' },
  { name: 'Yoane Wissa', team: 'COD', flag: '🇨🇩', info: 'Newcastle United · Angrep' },
];

// Fuzzy search: score a player against a query
function fuzzyScore(player, query) {
  const q = query.toLowerCase().trim();
  const n = player.name.toLowerCase();
  const parts = n.split(' ');
  if (n.startsWith(q)) return 100;
  if (parts.some(p => p.startsWith(q))) return 90;
  if (n.includes(q)) return 80;
  // Check each word of query against name
  const words = q.split(' ').filter(Boolean);
  if (words.length > 1 && words.every(w => n.includes(w))) return 70;
  // Partial match on any part
  if (parts.some(p => p.includes(q))) return 60;
  // Check first letters of each word
  const initials = parts.map(p=>p[0]).join('');
  if (initials.includes(q)) return 40;
  return 0;
}

function searchPlayers(query) {
  if (!query || query.trim().length < 1) return [];
  const scored = PLAYERS.map(p => ({ ...p, score: fuzzyScore(p, query) }))
    .filter(p => p.score > 0)
    .sort((a,b) => b.score - a.score);
  return scored.slice(0, 7);
}

